<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Microsoft.Practices.Prism.StoreApps</AssemblyName>
    <RootNamespace>Microsoft.Practices.Prism.StoreApps</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <!-- <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\Microsoft.Practices.Prism.StoreApps.xml</DocumentationFile> -->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Prism.PubSubEvents\Microsoft.Practices.Prism.PubSubEvents.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Strings\en-US\Resources.resw">
      <Generator>ResXFileCodeGenerator</Generator>
      <!-- <LastGenOutput>Resources.Designer.cs</LastGenOutput> -->
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\IFlyoutService.cs" />
  </ItemGroup>
</Project>